pre-release-commit-message = "chore: Release {{crate_name}} {{version}}"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = false
allow-branch = ["main"]
sign-commit = true
sign-tag = true
pre-release-replacements = [
    { file = "src/lib.rs", search = "version = .+,", replace = "version = \"{{version}}\",", exactly = 1 },
    { file = "sonar-project.properties", search = "sonar.projectVersion=.+", replace = "sonar.projectVersion=\"{{version}}\",", exactly = 1 },
]
