pre-release-commit-message = "chore: Release {{crate_name}} {{version}}"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
consolidate-commits = false
allow-branch = ["main"]
pre-release-replacements = [
    { file = "sonar-project.properties", search = "sonar.projectVersion=.+", replace = "sonar.projectVersion=\"{{version}}\",", exactly = 1 },
]
